import fs from 'node:fs/promises';
import path from 'node:path';
import makeWASocket, { DisconnectReason, downloadMediaMessage, fetchLatestBaileysVersion, generateWAMessageFromContent, makeCacheableSignalKeyStore, useMultiFileAuthState } from '@whiskeysockets/baileys';
import pino from 'pino';
import qrcode from 'qrcode-terminal';
import { persistWhatsAppMessage, persistMessageProcessing, persistMediaAsset, persistMultimodalExtraction } from './persistence-client.mjs';
import { analyzeImageBuffer, transcribeAudioBuffer } from './multimodal.mjs';
import { buildInteractiveMessage, buildInteractiveRelayNodes, canonicalInteractiveButtons, parseInteractiveReply } from './interactive-message.mjs';

/** @typedef {'DISCONNECTED' | 'CONNECTING' | 'PAIRING' | 'CONNECTED' | 'ERROR'} ConnectionState */
/** @typedef {'INBOUND' | 'OUTBOUND'} MessageDirection */
/** @typedef {'UNKNOWN' | 'RECEIVED'} MessageStatus */
/** @typedef {'TEXT' | 'AUDIO' | 'IMAGE' | 'VIDEO' | 'DOCUMENT' | 'INTERACTIVE_RESPONSE' | 'INTERACTIVE' | 'OTHER'} MessageType */
/** @typedef {{ id: string, jid: string | null, phone_normalized?: string | null, direction: MessageDirection, fromMe: boolean, text: string | null, timestamp: number, status: MessageStatus, push_name?: string | null, message_type?: MessageType, media_status?: string, media_error?: string | null, button_id?: string | null, button_text?: string | null, source_message_id?: string | null, interactive_provenance?: string | null, mime_type?: string | null, correlation_id?: string | null, causation_id?: string | null }} MessageSnapshot */
/** @typedef {{ connection: ConnectionState, qr: string | null, me: { id: string, name: string | null } | null, lastError: string | null, messageCount: number }} GatewayStatus */
/** @typedef {{ type: 'connection', status: GatewayStatus } | { type: 'message', message: MessageSnapshot }} GatewayEvent */

const logger = pino({ level: process.env.KASSIST_WA_LOG_LEVEL ?? 'warn' });
const authDir = path.resolve(process.env.KASSIST_WA_AUTH_DIR ?? './.data/whatsapp/auth');
const configuredMediaRoot = process.env.KASSIST_MEDIA_ROOT ? path.resolve(process.env.KASSIST_MEDIA_ROOT) : null;
const state = { connection: 'DISCONNECTED', qr: null, me: null, lastError: null, messages: [], messageIds: new Set() };
let socket = null;
let connecting = null;
let pendingCredsSave = Promise.resolve();
let reconnectTimer = null;
let lifecycleGeneration = 0;
let shuttingDown = false;
const eventListeners = new Set();
function emit(event) { for (const listener of eventListeners) { try { listener(event); } catch { /* isolated subscriber */ } } }
export function subscribe(listener) { eventListeners.add(listener); return () => eventListeners.delete(listener); }
export function getStatus() { return { connection: state.connection, qr: state.qr, me: state.me, lastError: state.lastError, messageCount: state.messages.length }; }
export function getMessages(limit = 100) { const safeLimit = Math.max(1, Math.min(Number(limit) || 100, 500)); return state.messages.slice(-safeLimit); }
export function normalizeRecipient(value) { const raw = String(value ?? '').trim(); if (!raw) throw new Error('Recipient is required'); if (raw.endsWith('@lid') || raw.endsWith('@g.us') || raw.endsWith('@s.whatsapp.net')) return raw; const digits = raw.replace(/\D/g, ''); if (!digits) throw new Error('Recipient must contain a WhatsApp JID, LID or phone digits'); return `${digits}@s.whatsapp.net`; }
export function messageType(message) { const content = message?.message ?? message ?? {}; if (parseInteractiveReply(message)) return 'INTERACTIVE_RESPONSE'; if (content.interactiveMessage) return 'INTERACTIVE'; if (content.audioMessage) return 'AUDIO'; if (content.imageMessage) return 'IMAGE'; if (content.videoMessage) return 'VIDEO'; if (content.documentMessage) return 'DOCUMENT'; return 'TEXT'; }
function messageMimeType(message, type = messageType(message)) { const content = message?.message ?? message ?? {}; if (type === 'IMAGE') return typeof content.imageMessage?.mimetype === 'string' ? content.imageMessage.mimetype : null; if (type === 'AUDIO') return typeof content.audioMessage?.mimetype === 'string' ? content.audioMessage.mimetype : null; if (type === 'VIDEO') return typeof content.videoMessage?.mimetype === 'string' ? content.videoMessage.mimetype : null; if (type === 'DOCUMENT') return typeof content.documentMessage?.mimetype === 'string' ? content.documentMessage.mimetype : null; return null; }
function extensionFromMimeType(mimeType, fallback = 'bin') { const normalized = String(mimeType ?? '').toLowerCase(); return ({ 'audio/ogg': 'ogg', 'audio/opus': 'opus', 'audio/mpeg': 'mp3', 'audio/mp4': 'm4a', 'audio/x-m4a': 'm4a', 'audio/wav': 'wav', 'audio/wave': 'wav', 'audio/webm': 'webm' })[normalized] ?? fallback; }
function observedPhoneIdentity(jid, key) { const alt = typeof key.remoteJidAlt === 'string' ? key.remoteJidAlt.trim() : ''; if (alt.endsWith('@s.whatsapp.net')) return alt; if (typeof jid === 'string' && jid.endsWith('@s.whatsapp.net')) return jid; return null; }
function snapshotMessage(message, direction) { const key = message.key ?? {}; const jid = key.remoteJid ?? null; const interactive = parseInteractiveReply(message); const type = interactive ? 'INTERACTIVE_RESPONSE' : messageType(message); const text = interactive?.buttonText ?? message.message?.interactiveMessage?.body?.text ?? message.message?.conversation ?? message.message?.extendedTextMessage?.text ?? message.message?.imageMessage?.caption ?? message.message?.videoMessage?.caption ?? null; return { id: key.id ?? `wa-${Date.now()}`, jid, phone_normalized: observedPhoneIdentity(jid, key), direction, fromMe: Boolean(key.fromMe), text, timestamp: Number(message.messageTimestamp ?? Math.floor(Date.now() / 1000)), status: direction === 'INBOUND' ? 'RECEIVED' : 'UNKNOWN', push_name: typeof message.pushName === 'string' ? message.pushName : null, message_type: type, media_status: type === 'TEXT' || type === 'INTERACTIVE' || type === 'INTERACTIVE_RESPONSE' ? 'NOT_APPLICABLE' : 'PENDING', media_error: null, mime_type: messageMimeType(message, type), correlation_id: `wa:${key.id ?? `generated-${Date.now()}`}`, causation_id: null, ...(interactive ? { button_id: interactive.buttonId, button_text: interactive.buttonText, source_message_id: interactive.sourceMessageId, interactive_provenance: interactive.provenance } : {}) }; }
function getDisconnectStatusCode(error) { if (typeof error !== 'object' || error === null || !('output' in error)) return undefined; const output = error.output; if (typeof output !== 'object' || output === null || !('statusCode' in output)) return undefined; return typeof output.statusCode === 'number' ? output.statusCode : undefined; }
export function recordMessage(snapshot) { if (state.messageIds.has(snapshot.id)) return false; state.messageIds.add(snapshot.id); state.messages.push(snapshot); if (state.messages.length > 500) { const removed = state.messages.shift(); if (removed) state.messageIds.delete(removed.id); } emit({ type: 'message', message: snapshot }); return true; }
function updateRecordedMessage(snapshot) { const index = state.messages.findIndex((item) => item.id === snapshot.id); if (index < 0) return recordMessage(snapshot); state.messages[index] = snapshot; emit({ type: 'message', message: snapshot }); return true; }
async function persistSnapshot(snapshot, metadata = {}) { const result = await persistWhatsAppMessage({ message: { ...snapshot, external_message_id: snapshot.id }, ...metadata }); if (!result.persisted) console.warn(`[KassisT Persistence] duplicate or already persisted message ${snapshot.id}`); return result; }
async function processInboundMedia(message, snapshot, isCurrentLifecycle) {
  const mediaType = snapshot.message_type;
  if (!['AUDIO', 'IMAGE'].includes(mediaType)) return snapshot;
  const startedAt = new Date().toISOString();
  const correlationId = snapshot.correlation_id ?? `wa:${snapshot.id}`;
  try {
    await persistMessageProcessing({ messageId: snapshot.id, stage: 'MEDIA_DOWNLOAD', status: 'PROCESSING', correlationId, causationId: snapshot.causation_id, startedAt });
    if (!isCurrentLifecycle()) return snapshot;
    const buffer = await downloadMediaMessage(message, 'buffer', {});
    if (!Buffer.isBuffer(buffer) || buffer.length === 0) throw Object.assign(new Error('WhatsApp media payload is empty'), { code: 'MEDIA_EMPTY' });
    const mimeType = snapshot.mime_type;
    const media = await persistMediaAsset({ messageId: snapshot.id, mediaType, mimeType, base64: buffer.toString('base64') });
    await persistMessageProcessing({ messageId: snapshot.id, stage: 'MEDIA_DOWNLOAD', status: 'COMPLETED', correlationId, causationId: snapshot.causation_id, startedAt, completedAt: new Date().toISOString() });
    console.log(`[KassisT WhatsApp] MEDIA_DOWNLOAD_COMPLETED message_id=${snapshot.id} media_type=${mediaType} size=${media.sizeBytes} sha256=${media.sha256}`);
    if (!isCurrentLifecycle()) return { ...snapshot, media_status: 'COMPLETED' };
    if (mediaType === 'AUDIO') {
      await persistMessageProcessing({ messageId: snapshot.id, stage: 'AUDIO_TRANSCRIPTION', status: 'PROCESSING', correlationId, causationId: snapshot.id, startedAt: new Date().toISOString() });
      console.log(`[KassisT WhatsApp] AUDIO_TRANSCRIPTION_STARTED message_id=${snapshot.id}`);
      const result = await transcribeAudioBuffer(buffer, { extension: extensionFromMimeType(mimeType, 'ogg') });
      await persistMultimodalExtraction({ messageId: snapshot.id, mediaAssetId: media.id, modality: 'TRANSCRIPTION', status: result.status === 'COMPLETED' ? 'COMPLETED' : result.status, extractedText: result.text, confidence: result.confidence, provider: result.provider, model: result.model, errorCode: result.error ? (result.status === 'UNAVAILABLE' ? 'TRANSCRIPTION_UNAVAILABLE' : result.status === 'TIMEOUT' ? 'TRANSCRIPTION_TIMEOUT' : 'TRANSCRIPTION_FAILED') : null, errorMessage: result.error, correlationId, causationId: snapshot.id });
      await persistMessageProcessing({ messageId: snapshot.id, stage: 'AUDIO_TRANSCRIPTION', status: result.status === 'COMPLETED' ? 'COMPLETED' : result.status, correlationId, causationId: snapshot.id, startedAt, completedAt: new Date().toISOString(), provider: result.provider, model: result.model, errorCode: result.error ? (result.status === 'UNAVAILABLE' ? 'TRANSCRIPTION_UNAVAILABLE' : result.status === 'TIMEOUT' ? 'TRANSCRIPTION_TIMEOUT' : 'TRANSCRIPTION_FAILED') : null, errorMessage: result.error });
      console.log(`[KassisT WhatsApp] AUDIO_TRANSCRIPTION_${result.status === 'COMPLETED' ? 'COMPLETED' : 'FAILED'} message_id=${snapshot.id}`);
      return { ...snapshot, text: result.text ?? snapshot.text, media_status: result.status, media_error: result.error ?? null };
    }
    await persistMessageProcessing({ messageId: snapshot.id, stage: 'IMAGE_ANALYSIS', status: 'PROCESSING', correlationId, causationId: snapshot.id, startedAt: new Date().toISOString() });
    console.log(`[KassisT WhatsApp] IMAGE_ANALYSIS_STARTED message_id=${snapshot.id} model=${process.env.KASSIST_LLM_VISION_MODEL || process.env.KASSIST_LLM_MODEL || 'unconfigured'}`);
    const result = await analyzeImageBuffer(buffer, { mimeType });
    await persistMultimodalExtraction({ messageId: snapshot.id, mediaAssetId: media.id, modality: 'VISION', status: result.status === 'COMPLETED' ? 'COMPLETED' : result.status, extractedText: result.text, structured: result.structured, confidence: result.confidence, provider: result.provider, model: result.model, errorCode: result.errorCode ?? null, errorMessage: result.error ?? null, correlationId, causationId: snapshot.id });
    await persistMessageProcessing({ messageId: snapshot.id, stage: 'IMAGE_ANALYSIS', status: result.status === 'COMPLETED' ? 'COMPLETED' : result.status, correlationId, causationId: snapshot.id, startedAt, completedAt: new Date().toISOString(), provider: result.provider, model: result.model, errorCode: result.errorCode ?? null, errorMessage: result.error ?? null });
    console.log(`[KassisT WhatsApp] IMAGE_ANALYSIS_${result.status === 'COMPLETED' ? 'COMPLETED' : 'FAILED'} message_id=${snapshot.id} status=${result.status} model=${result.model ?? 'none'}`);
    return { ...snapshot, text: result.text ?? snapshot.text, media_status: result.status, media_error: result.error ?? null };
  } catch (error) {
    const errorCode = error && typeof error === 'object' && typeof error.code === 'string' ? error.code : 'MEDIA_PROCESSING_FAILED';
    const errorMessage = error instanceof Error ? error.message : String(error);
    await persistMessageProcessing({ messageId: snapshot.id, stage: 'MEDIA_DOWNLOAD', status: 'FAILED', correlationId, causationId: snapshot.causation_id, startedAt, completedAt: new Date().toISOString(), errorCode, errorMessage }).catch(() => {});
    return { ...snapshot, media_status: 'FAILED', media_error: errorMessage };
  }
}
async function clearAuthState() { await fs.rm(authDir, { recursive: true, force: true }); }
async function safelyEndSocket(targetSocket = socket) { const current = targetSocket; if (current === socket) socket = null; if (!current) return; try { current.end(undefined); } catch {} }
async function startSocket({ generation } = { generation: lifecycleGeneration }) { await fs.mkdir(authDir, { recursive: true }); const { state: authState, saveCreds } = await useMultiFileAuthState(authDir); const { version } = await fetchLatestBaileysVersion(); if (generation !== lifecycleGeneration || shuttingDown) return; const socketInstance = makeWASocket({ version, auth: { creds: authState.creds, keys: makeCacheableSignalKeyStore(authState.keys, logger) }, logger, markOnlineOnConnect: false, syncFullHistory: false }); socket = socketInstance; socketInstance.ev.on('creds.update', () => { const saveGeneration = generation; pendingCredsSave = pendingCredsSave.then(async () => { if (saveGeneration !== lifecycleGeneration || socketInstance !== socket || shuttingDown) return; await saveCreds(); }).catch((error) => console.error('[KassisT WhatsApp] failed to persist auth credentials:', error instanceof Error ? error.message : String(error))); }); socketInstance.ev.on('connection.update', async ({ connection, qr, lastDisconnect }) => { if (generation !== lifecycleGeneration) { await safelyEndSocket(socketInstance); return; } if (qr) { state.qr = qr; state.connection = 'PAIRING'; state.lastError = null; qrcode.generate(qr, { small: true }); emit({ type: 'connection', status: getStatus() }); } if (connection === 'open') { state.connection = 'CONNECTED'; state.qr = null; state.lastError = null; state.me = socketInstance.user ? { id: socketInstance.user.id, name: socketInstance.user.name ?? null } : null; emit({ type: 'connection', status: getStatus() }); return; } if (connection === 'close') { const statusCode = getDisconnectStatusCode(lastDisconnect?.error); const loggedOut = statusCode === DisconnectReason.loggedOut; const error = lastDisconnect?.error?.message ?? String(lastDisconnect?.error ?? 'Connection closed'); if (socketInstance === socket) socket = null; if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; } if (shuttingDown) { state.connection = 'DISCONNECTED'; state.qr = null; state.me = null; state.lastError = null; emit({ type: 'connection', status: getStatus() }); return; } state.connection = loggedOut ? 'DISCONNECTED' : 'CONNECTING'; state.lastError = loggedOut ? null : error; state.qr = null; state.me = null; emit({ type: 'connection', status: getStatus() }); if (!loggedOut) reconnectTimer = setTimeout(() => { reconnectTimer = null; connect().catch((reconnectError) => { state.connection = 'ERROR'; state.lastError = reconnectError instanceof Error ? reconnectError.message : String(reconnectError); emit({ type: 'connection', status: getStatus() }); }); }, 1500); } }); socketInstance.ev.on('messages.upsert', ({ messages }) => { const isCurrentLifecycle = () => generation === lifecycleGeneration && socketInstance === socket && !shuttingDown; for (const message of messages) { if (!isCurrentLifecycle()) return; const initial = snapshotMessage(message, message.key?.fromMe ? 'OUTBOUND' : 'INBOUND'); void (async () => {
      if (!isCurrentLifecycle()) return;
      try {
        await persistSnapshot(initial);
      } catch (error) {
        console.error(`[KassisT Persistence] failed to persist WhatsApp message ${initial.id}:`, error instanceof Error ? error.message : String(error));
        return;
      }
      if (!isCurrentLifecycle()) return;
      recordMessage(initial);
      if (initial.direction !== 'INBOUND' || !['AUDIO', 'IMAGE'].includes(initial.message_type)) return;
      const processed = await processInboundMedia(message, initial, isCurrentLifecycle);
      updateRecordedMessage(processed);
      console.log(`[KassisT WhatsApp] multimodal processing finished message_id=${initial.id} status=${processed.media_status ?? 'UNKNOWN'}`);
    })(); } }); }
export async function connect() { if (shuttingDown) return; if (connecting) return connecting; if (socket && state.connection === 'CONNECTED') return; if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; } lifecycleGeneration += 1; const generation = lifecycleGeneration; connecting = (async () => { state.connection = 'CONNECTING'; state.qr = null; state.me = null; state.lastError = null; emit({ type: 'connection', status: getStatus() }); try { await startSocket({ generation }); } catch (error) { if (generation === lifecycleGeneration) { state.connection = 'ERROR'; state.lastError = error instanceof Error ? error.message : String(error); emit({ type: 'connection', status: getStatus() }); } throw error; } finally { connecting = null; } })(); return connecting; }
export async function shutdown() { shuttingDown = true; lifecycleGeneration += 1; if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; } const activeSocket = socket; socket = null; if (activeSocket) { try { activeSocket.end(undefined); } catch (error) { console.error('[KassisT WhatsApp] failed to close socket cleanly:', error instanceof Error ? error.message : String(error)); } } await pendingCredsSave; state.connection = 'DISCONNECTED'; state.qr = null; state.me = null; emit({ type: 'connection', status: getStatus() }); }
export async function logout() { lifecycleGeneration += 1; if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; } const current = socket; socket = null; if (current) { try { await current.logout('KassisT user requested logout'); } catch (error) { console.error('[KassisT WhatsApp] failed to logout cleanly:', error instanceof Error ? error.message : String(error)); } } state.connection = 'DISCONNECTED'; state.qr = null; state.me = null; state.lastError = null; emit({ type: 'connection', status: getStatus() }); }
export async function resetSession() { await logout(); await pendingCredsSave; await clearAuthState(); state.connection = 'DISCONNECTED'; state.qr = null; state.me = null; state.lastError = null; emit({ type: 'connection', status: getStatus() }); }
export async function sendText(to, text) { if (!socket || state.connection !== 'CONNECTED') throw new Error('WhatsApp transport is not connected'); const jid = normalizeRecipient(to); const body = String(text ?? '').trim(); if (!body) throw new Error('Message text is required'); const result = await socket.sendMessage(jid, { text: body }); if (!result) throw new Error('WhatsApp transport did not return a message'); const snapshot = snapshotMessage(result, 'OUTBOUND'); await persistSnapshot(snapshot); recordMessage(snapshot); return snapshot; }
function mediaMimeType(reference) { return { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp', '.gif': 'image/gif' }[path.extname(reference).toLowerCase()] ?? null; }
function isInsideRoot(reference, root) { const relative = path.relative(root, reference); return relative === '' || (!relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative)); }
function assertMediaReference(value) { const result = String(value ?? '').trim(); if (!result) throw new Error('Image reference is required'); return result; }
async function readControlledImage(imageReference) { const reference = path.resolve(assertMediaReference(imageReference)); if (!configuredMediaRoot) throw new Error('Controlled media transport root is not configured'); if (!isInsideRoot(reference, configuredMediaRoot)) throw new Error('Image reference is outside the authorized media root'); const stat = await fs.stat(reference).catch((error) => { throw new Error(`Image asset is unavailable: ${error instanceof Error ? error.message : String(error)}`); }); if (!stat.isFile() || stat.size <= 0) throw new Error('Image asset must be a non-empty file'); const mimetype = mediaMimeType(reference); if (!mimetype) throw new Error('Unsupported image format'); return { reference, mimetype, data: await fs.readFile(reference) }; }
export async function sendImage(to, imageReference, caption = null) { if (!socket || state.connection !== 'CONNECTED') throw new Error('WhatsApp transport is not connected'); const asset = await readControlledImage(imageReference); const jid = normalizeRecipient(to); const body = caption == null ? null : String(caption).trim(); const result = await socket.sendMessage(jid, { image: asset.data, mimetype: asset.mimetype, ...(body ? { caption: body } : {}) }); if (!result) throw new Error('WhatsApp image transport did not return a message'); const snapshot = snapshotMessage(result, 'OUTBOUND'); await persistSnapshot(snapshot); recordMessage(snapshot); return snapshot; }
export async function sendInteractive(to, body, buttons, { imageReference = null, caption = null } = {}) { if (!socket || state.connection !== 'CONNECTED') throw new Error('WhatsApp transport is not connected'); if (imageReference != null || caption != null) throw new Error('Interactive transport currently supports text-only quick replies'); const jid = normalizeRecipient(to); const text = String(body ?? '').trim(); if (!text) throw new Error('Interactive message body is required'); const canonicalButtons = canonicalInteractiveButtons(buttons); const interactiveMessage = buildInteractiveMessage({ body: text, buttons: canonicalButtons }); const generated = await generateWAMessageFromContent(jid, { interactiveMessage, messageContextInfo: { deviceListMetadataVersion: 2 } }, { userJid: socket.user?.id ?? '' }); const messageId = generated.key?.id; if (!messageId || !generated.message) throw new Error('Interactive message generation did not return a message'); await socket.relayMessage(jid, generated.message, { messageId, additionalNodes: buildInteractiveRelayNodes() }); const snapshot = { ...snapshotMessage(generated, 'OUTBOUND'), message_type: 'INTERACTIVE', text }; try { await persistSnapshot(snapshot); } catch (error) { console.error(`[KassisT Persistence] interactive provider effect observed but persistence failed for ${messageId}:`, error instanceof Error ? error.message : String(error)); return { ...snapshot, persistenceState: 'FAILED_AFTER_PROVIDER_OBSERVED' }; } recordMessage(snapshot); return { ...snapshot, persistenceState: 'PERSISTED' }; }
